replicaCount: 1

image:
  tag: staging

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "250m"

autoscaling:
  enabled: false

config:
  logLevel: "DEBUG"
  redisPoolSize: "10"
